### PR TITLE
Add Docs/resource branch category

### PR DESCRIPTION
**Pull request by mmunozba**
Adds a category for branches regarding resource files. (e.g. a CSAR file for testing)

### CODE REVIEW

**Comment by JensMueller2709** [comment]
i think this is a good idea for example regarding the LAMP-csar development.

**Comment by hnicke** [comment]
What about using not using 'resource`, but `test`?

**Comment by nfode** [comment]
I don't mind. What does the rest say?

**Comment by mmunozba** [comment]
Sounds good.

**Comment by c-mueller** [comment]
I wont wait for anyone else to approve this. Seems to be clear that it is accepted.

Therefore;
Merged!

**Pull request merged**
