### PR TITLE
K8s implementation

### PR DESCRIPTION
**Pull request by nfode**
Pull request for the simple k8s plugin.

**TODO:**
- [x] Implement the transform method
   - [x] parse the TServiceTemplate
   - [x] generate the fitting manual
   - [x] generate the fitting resource file
   - [x] copy everything to the right directory

### CODE REVIEW

**Comment by nfode** [comment]
@c-mueller @hnicke I think this can be merged into master. If is merged it eases further development on the Kubernetes Plugin!

**Comment by nfode** [comment]
I also would recommend to squash this 😄

**Comment by c-mueller** [comment]
WIll merge it once i am at home. maybe @hnicke could do it now (or at least faster than me)

its probably a good idea to merge everything into one branch and perform a Feature driven way in the complete application.

**Comment by hnicke** [comment]
I'm currently doing a review on this PR.

**Comment by nfode** [comment]
@hnicke oh no :sweat_smile:

**Pull request merged**
