### PR TITLE
Fix aws to support common lamp model

### PR DESCRIPTION
**Pull request by mklopp**

### CODE REVIEW

**Comment by mklopp** [comment]
I actually already looked at that. It's a cloudfoundry test from @JensMueller2709 that is failing to to the changes to the common lamp model

**Comment by mmunozba** [comment]
Is there a way to fix this? Can we maybe move some of the changes from this PR to #386?

**Comment by c-mueller** [comment]
Can we merge this?

**Comment by mklopp** [comment]
with the new changes to common lamp model this is wip again

**Comment by c-mueller** [comment]
Considering this done. I am therefore merging it.

**Pull request merged**
